### ISSUE TITLE
no support for static consumer group membership

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.messagehub#109]
According to https://cloud.ibm.com/docs/EventStreams?topic=EventStreams-plan_choose, most plans are on Kafka 2.3, which supports static group members. The streamsx.kafka toolkit supports this feature, in streamsx.messagehub, it is still disabled.

https://github.com/IBMStreams/streamsx.messagehub/blob/0934f3f9c14651204d17ff5dd2f65aff14bc3497/com.ibm.streamsx.messagehub/impl/java/src/com/ibm/streamsx/messagehub/operators/MessageHubConsumerOperator.java#L127-L134

**Comment by ghost** [comment]
resolved in release v3.1.0
