### ISSUE TITLE
Release of toolkit is missing icons.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#16]
If you try to reindex the toolkit with `spl-make-toolkit` you get warnings about the missing icons under `icons`.

**Comment by ddebrunner** [comment]
I still get this with the 1.2.3 release.

1. Download the release
1. Untar the release
1. `spl-make-toolkit -i com.ibm.streamsx.messagehub`

```
I'll add output.
```

**Comment by RolefH** [comment]
The complete 'icons' directory is missing. corrected in current 'develop' branch.

**Comment by RolefH** [comment]
corrected in v1.2.4
