### ISSUE TITLE
Create streamsx.messagehub Python package.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#18]
Create a `streamsx.messagehub` package exposing this toolkit as Python functions/classes that integrate with the Python application api.

Initial work is here: https://github.com/ddebrunner/streamsx.messagehub/tree/pypackage

Can be installed as 

```
pip install git+https://github.com/ddebrunner/streamsx.messagehub@pypackage#subdirectory=python/package
```

Eventual plan would be to upload to pypi.

I propose a feature branch `pypackage` be created.

Concept is to expose the common cases as simple Python constructs, rather than make the full complexity of the operators available.

**Comment by cancilla** [comment]
Done.

**Comment by ddebrunner** [comment]
The branch was created but the overall task was not :-)

**Comment by RolefH** [comment]
Python package is created.
