### ISSUE TITLE
MessageHubConsumer startTime does not document time units.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#30]
There's no indication how a timestamp is represented with `startTime` parameter as an `int64`.

It's probably milliseconds since unix epoch, but I'm not 100% sure, it needs to be stated in the documentation.

**Comment by RolefH** [comment]
Must be corrected in Kafka toolkit. Kafka timestamps are given in milliseconds since Unix epoch.

**Comment by RolefH** [comment]
corrected in v1.2.4
