### ISSUE TITLE
Link to kafka toolkit in operators' doc is broken

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.messagehub#33]
In 
https://ibmstreams.github.io/streamsx.messagehub/docs/v1.2.3/spldoc/html/tk$com.ibm.streamsx.messagehub/op$com.ibm.streamsx.messagehub$MessageHubConsumer.html
Under **Additional Operator Details **, the link to the Kafka toolkit is broken.

**Comment by RolefH** [comment]
corrected in v1.2.4
