### ISSUE TITLE
Improve user facing page.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#36]
https://ibmstreams.github.io/streamsx.messagehub/

- [ ] No link to the project page as all the other toolkits have
- [ ] Page is "dominated" by older releases meaning a casual visitor is likely to miss the samples section. Maybe move the older releases to a separate page with a single link from the main page.

**Comment by RolefH** [comment]
@ddebrunner: Do we want to maintain the content of https://github.com/IBMStreams/streamsx.messagehub/wiki/Standard-Consumer-Use-Cases-with-partitions in gh-pages? As a first step I added only a link to this wiki page to the gh-pages documentation. 

`gh-pages` branch, `_docs/230-user_standard_consumer_use_patterns.md`

**Comment by ddebrunner** [comment]
That wiki page is somewhat a work in progress, we still need to define the common use cases customers need.
