### ISSUE TITLE
Reduce toolkit size

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.messagehub#40]
The size of the toolkit is 17 MB. `opt/downloaded` contains following files:

    [com.ibm.streamsx.messagehub]$ ls -l opt/downloaded/
    total 19432
    -rw-rw-r--. 1 rolef rolef   85727 Feb 16 08:11 com.ibm.streamsx.kafka-1.2.4.jar
    -rw-rw-r--. 1 rolef rolef  479881 Feb 16 08:11 commons-lang3-3.5.jar
    -rw-rw-r--. 1 rolef rolef  231952 Feb 16 08:11 gson-2.8.0.jar
    -rw-rw-r--. 1 rolef rolef 2521113 Feb 16 08:11 guava-21.0.jar
    -rw-rw-r--. 1 rolef rolef   78175 Feb 16 08:11 jopt-simple-5.0.3.jar
    -rw-rw-r--. 1 rolef rolef 5584385 Feb 16 08:11 kafka_2.10-0.10.2.0.jar
    -rw-rw-r--. 1 rolef rolef  946811 Feb 16 08:11 kafka-clients-0.10.2.0.jar
    -rw-rw-r--. 1 rolef rolef  489884 Feb 16 08:11 log4j-1.2.17.jar
    -rw-rw-r--. 1 rolef rolef  236880 Feb 16 08:11 lz4-1.3.0.jar
    -rw-rw-r--. 1 rolef rolef   82123 Feb 16 08:11 metrics-core-2.2.0.jar
    -rw-rw-r--. 1 rolef rolef 7132001 Feb 16 08:11 scala-library-2.10.6.jar
    -rw-rw-r--. 1 rolef rolef   41071 Feb 16 08:11 slf4j-api-1.7.21.jar
    -rw-rw-r--. 1 rolef rolef    9988 Feb 16 08:11 slf4j-log4j12-1.7.21.jar
    -rw-rw-r--. 1 rolef rolef 1056168 Feb 16 08:11 snappy-java-1.1.2.6.jar
    -rw-rw-r--. 1 rolef rolef   74798 Feb 16 08:11 zkclient-0.10.jar
    -rw-rw-r--. 1 rolef rolef  807277 Feb 16 08:11 zookeeper-3.4.9.jar

I'm wonderin whether the big blobs `kafka_2.10-0.10.2.0.jar` and `scala-library-2.10.6.jar` are really required. Also `zkclient` and `zookeeper` should be verified - they might have been pulled in as dependency of `kafka_2.10*.jar`.

**Comment by ddebrunner** [comment]
log4j 1.2 is also part of the Streams Java Operator API so any version in the toolkit will be ignored.

**Comment by RolefH** [comment]
This would be the new directory content:

    [rolef@oc4756048336 com.ibm.streamsx.messagehub]$ ls -l opt/downloaded/
    total 5500
    -rw-rw-r--. 1 rolef rolef  101737 Feb 23 11:29 com.ibm.streamsx.kafka-1.3.0.jar
    -rw-rw-r--. 1 rolef rolef  479881 Feb 23 11:29 commons-lang3-3.5.jar
    -rw-rw-r--. 1 rolef rolef  231952 Feb 23 11:29 gson-2.8.0.jar
    -rw-rw-r--. 1 rolef rolef 2521113 Feb 23 11:29 guava-21.0.jar
    -rw-rw-r--. 1 rolef rolef  946811 Feb 23 11:29 kafka-clients-0.10.2.0.jar
    -rw-rw-r--. 1 rolef rolef  236880 Feb 23 11:29 lz4-1.3.0.jar
    -rw-rw-r--. 1 rolef rolef   41071 Feb 23 11:29 slf4j-api-1.7.21.jar
    -rw-rw-r--. 1 rolef rolef 1056168 Feb 23 11:29 snappy-java-1.1.2.6.jar

**Comment by RolefH** [comment]
solved with v1.3.0
