### ISSUE TITLE
MessageHub sample doesn't work

### ISSUE THREAD

**Issue by just4li** [IBMStreams/streamsx.messagehub#42]
Following the sample link:
https://github.com/IBMStreams/streamsx.messagehub/blob/develop/samples/MessageHubAppConfigSample/com.ibm.streamsx.messagehub.sample/MessageHubAppConfigSample.spl

The build works OK, generate sab file without an issue and configured the 'messagehub' application configuration  pointing to my Messagehub instance credential with messagehub.creds :
{
  "instance_id": "c75cc677-db7f-47e9-8e41-*********",
  "mqlight_lookup_url": "https://mqlight-lookup-prod02.messagehub.services.us-south.bluemix.net/Lookup?serviceId=c75cc677-db7f-47e9-8e41-**************",
  "api_key": "*******************",
  "kafka_admin_url": "https://kafka-admin-prod02.messagehub.services.us-south.bluemix.net:443",
  "kafka_rest_url": "https://kafka-rest-prod02.messagehub.services.us-south.bluemix.net:443",
  "kafka_brokers_sasl": [
    "kafka04-prod02.messagehub.services.us-south.bluemix.net:9093",
    "kafka02-prod02.messagehub.services.us-south.bluemix.net:9093",
    "kafka01-prod02.messagehub.services.us-south.bluemix.net:9093",
    "kafka05-prod02.messagehub.services.us-south.bluemix.net:9093",
    "kafka03-prod02.messagehub.services.us-south.bluemix.net:9093"
  ],
  "user": "*************",
  "password": "---------------------"
}

but got the following error:

08 Mar 2018 12:26:34.304 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2 M[ProducerCallback.java:com.ibm.streamsx.kafka.clients.producer.ProducerCallback.onCompletion:19]  - Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.307 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2 M[?:?:0]  - org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.320 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2 M[KafkaProducerClient.java:com.ibm.streamsx.kafka.clients.producer.KafkaProducerClient.send:63]  - CDIST2152E Previous batch failed to send: Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.321 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2 M[?:?:0]  - org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.322 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.process:-1]  - Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.328 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2,spl_javaop M[?:?:0]  - org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
08 Mar 2018 12:26:34.329 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2,spl_function M[JavaOp.cpp:processTuple:1568]  - CDISR5126E: A Java exception occurred at Operator.process() during the JavaOp invocation.
08 Mar 2018 12:26:34.483 [13022] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2,#splapptrc,J[1],P[1],MessageHubProducer_2,spl_operator M[PEImpl.cpp:handleOperatorFailure:596]  - CDISR5030E: An exception occurred during the execution of the MessageHubProducer_2 operator. The exception is: A Java exception occurred at Operator.process() during the JavaOp invocation.
08 Mar 2018 12:26:35.630 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples submitted (port 0) metric of the MessageHubConsumer_3 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.630 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations submitted (port 0) metric of the MessageHubConsumer_3 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.630 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations submitted (port 0) metric of the MessageHubConsumer_3 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.630 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The nDroppedMalformedMessages metric of the MessageHubConsumer_3 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.631 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples processed (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.631 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples dropped (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.631 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples currently queued (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.632 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations processed (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.632 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations processed (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.632 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations queued (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.632 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations queued (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.632 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Size of the queue for a threaded port (port 0) metric of the Custom_4 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.633 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples submitted (port 0) metric of the Beacon_1 operator has a value of 1 at exit.
08 Mar 2018 12:26:35.633 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations submitted (port 0) metric of the Beacon_1 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.633 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations submitted (port 0) metric of the Beacon_1 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.633 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples processed (port 0) metric of the MessageHubProducer_2 operator has a value of 2 at exit.
08 Mar 2018 12:26:35.634 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples dropped (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.634 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of tuples currently queued (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations processed (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations processed (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of window punctuations queued (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Number of final punctuations queued (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR spl_metric M[OperatorMetricsImpl.cpp:dumpMetricAtExit:120]  - The Size of the queue for a threaded port (port 0) metric of the MessageHubProducer_2 operator has a value of 0 at exit.
08 Mar 2018 12:26:35.635 [12942] ERROR #splapptrc,J[1],P[1],MessageHubProducer_2,spl_operator M[PEImpl.cpp:process:1367]  - CDISR5053E: Runtime failures occurred in the following operators: MessageHubProducer_2.

**Comment by RolefH** [comment]
Can you please submit the job with debug trace level

`streamtool submitjob --config tracing=debug output/com.ibm.streamsx.messagehub.sample.MessageHubAppConfigSample/com.ibm.streamsx.messagehub.sample.MessageHubAppConfigSample.sab`

and post the ProducerConfig values from the PE trace (pe._peId_.out). It should be something like this:
```
08 Mar 2018 20:19:48.348 [1297] INFO #splapptrc,J[2],P[11],MessageHubProducer_2 M[AbstractKafkaProducerOperator.java:com.ibm.streamsx.kafka.operators.AbstractKafkaProducerOperator.initProducer:296]  - Creating AtLeastOnce producer
08 Mar 2018 20:19:48.350 [1297] DEBUG #splapptrc,J[2],P[11],MessageHubProducer_2 M[AbstractKafkaClient.java:com.ibm.streamsx.kafka.clients.AbstractKafkaClient.getRandomId:81]  - Random id=producer-8Hjg1WPZkAN5ShaJO
08 Mar 2018 20:19:48.384 [1297] INFO #splapptrc,J[2],P[11],MessageHubProducer_2 M[AbstractConfig.java:org.apache.kafka.common.config.AbstractConfig.logAll:180]  - ProducerConfig values: 
        acks = 1
        batch.size = 16384
        block.on.buffer.full = false
        bootstrap.servers = [kafka04-prod02.messagehub.services.us-south.bluemix.net:9093, kafka03-prod02.messagehub.services.us-south.bluemix.net:9093, kafka02-prod02.messagehub.services.us-south.bluemix.net:9093, kafka05-prod02.messagehub.services.us-south.bluemix.net:9093, kafka01-prod02.messagehub.services.us-south.bluemix.net:9093]
        buffer.memory = 33554432
        client.id = producer-8Hjg1WPZkAN5ShaJO
        compression.type = none
        connections.max.idle.ms = 540000
        interceptor.classes = null
        key.serializer = class org.apache.kafka.common.serialization.StringSerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 5
        max.request.size = 1048576
        metadata.fetch.timeout.ms = 60000
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 0
        retry.backoff.ms = 100
        sasl.jaas.config = [hidden]
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.mechanism = PLAIN
        security.protocol = SASL_SSL
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2]
        ssl.endpoint.identification.algorithm = HTTPS
        ssl.key.password = null
        ssl.keymanager.algorithm = IbmX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.2
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        timeout.ms = 30000
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer
```
For me the sample worked as expected with both app config at instance scope and at domain scope. I used Streams 4.2.1.1, the Message Hub toolkit v1.2.4, and a Message Hub cloud service at location US South.

Please post also the output of following two commands:

`streamtool getappconfig -d $STREAMS_DOMAIN_ID -i $STREAMS_INSTANCE_ID messagehub`

and

`streamtool getappconfig -d $STREAMS_DOMAIN_ID messagehub`

**Please replace sensitive information in the output, like user and password, by stars when you post.**

**Comment by just4li** [comment]
The way to make it work is the following:
1. uncommented // appConfigName : "my-app-config" ;    
2. add a composite param my-app-config
3. give "messagehub" as the value to my-app-config during job submit. 
That is the only way I can find to make the sample work

**Comment by just4li** [comment]
I commented out appConfigName line, build and resubmit the job. It works this time. I post your required configuration here anyway:

08 Mar 2018 15:26:45.605 [35098] INFO #splapptrc,J[5],P[4],MessageHubProducer_2 M[AbstractConfig.java:org.apache.kafka.common.config.AbstractConfig.logAll:180]  - ProducerConfig values: 
	acks = 1
	batch.size = 16384
	block.on.buffer.full = false
	bootstrap.servers = [kafka02-prod02.messagehub.services.us-south.bluemix.net:9093, kafka01-prod02.messagehub.services.us-south.bluemix.net:9093, kafka03-prod02.messagehub.services.us-south.bluemix.net:9093, kafka05-prod02.messagehub.services.us-south.bluemix.net:9093, kafka04-prod02.messagehub.services.us-south.bluemix.net:9093]
	buffer.memory = 33554432
	client.id = producer-XOSOFVssrLketN1pw
	compression.type = none
	connections.max.idle.ms = 540000
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.fetch.timeout.ms = 60000
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_SSL
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2]
	ssl.endpoint.identification.algorithm = HTTPS
	ssl.key.password = null
	ssl.keymanager.algorithm = IbmX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.2
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	timeout.ms = 30000
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

**Comment by RolefH** [comment]
The sample works for me. Verified with Streams 4.3, Event Streams Standard plan and app config 'messagehub' at instance level.
