### ISSUE TITLE
1.5 alpha MessageHubConsumer ignores startPosition when not in a consistent region.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#56]
The SPLDOC for 1.5 alpha has this for `startPosition` of `MessageHubConsumer`:

_The parameter is ignored when not in a consistent region._

This seems to be an undesired change in behaviour.

Why is the start position related to consistent region? A consumer outside of a consistent region should still be able to start at assigned positions.

**Comment by ddebrunner** [comment]
`startPosition` works when not in a consistent region with 1.4.

**Comment by RolefH** [comment]
*The parameter is ignored when not in a consistent region.*
Should belong to the parameter **consistentRegionAssignmentMode**. It's a documentation issue. No existing function from last toolkit version changes when consumer group + consistent region is enabled.
