### ISSUE TITLE
1.5alpha MessageHubConsumer consistentRegionAssignmentMode & GroupCoordinated

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messagehub#58]
MessageHubConsumer

`consistentRegionAssignmentMode` with `GroupCoordinated`.

The documentation says: _The operator will fail at runtime if it detects the default random group ID._

What is the default random group id?

I think it needs to be documented so I don't select it my `groupId`. E.g. I'm using `getJobName()` but that seems like a likely default choice by the operator?

**Comment by RolefH** [comment]
@ddebrunner 
When you do NOT specify a group-ID (you can do this either as consumer property `group.id` or as groupId parameter) the operator creates a group-ID `group-<17 random alphanum characters>`, each operator a different one. This is invalid when we want to create a consumer group.

All default setting are documented only in the SPLDoc of the Kafka toolkit.

**Comment by ddebrunner** [comment]
Thanks, the documentation of the MH toolkit should be sefl-contained, not having to refer back to a different toolkit.
