### ISSUE TITLE
Change trace level for metrics dump

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.messagehub#73]
This is what the MessageHubProducer operator is logging every two seconds:
 
04 Jan 2019 13:35:25.548+0000 [40924] INFO #splapptrc,J[86],P[329],StoredResultSink.KafkaResultSink M[KafkaProducerClient.java:com.ibm.streamsx.kafka.clients.producer.KafkaProducerClient$MetricsMonitor.afterCustomMetricsUpdated:88]  - QTimeMax= 0 ,QTimeAvg= 0 ,oByteRate= 0 ,reqRate= 0 ,recsPerReqAvg= 0 ,batchSzAvg= 0 ,bufAvail= 33,554,432 ,bufPoolWaitTimeTotal= 0

**Comment by markheger** [comment]
Increase the level to debug or trace

**Comment by RolefH** [comment]
The issue must be corrected in the Kafka toolkit. Based on a new Kafka toolkit version I can release a corrected MessageHub toolkit.

**Comment by RolefH** [comment]
solved in release v1.7.2
